# Permission
query getPermissions {
	getPermissions {
		count
		rows {
			...PermissionListItem
		}
	}
}

# Role
query getRoles {
	getRoles {
		count
		rows {
			...RoleListItem
		}
	}
}

# EntityType
query getEntityTypes {
	getEntityTypes {
		count
		rows {
			...EntityTypeListItem
		}
	}
}

# EntityTypeEntityType
query getEntityTypeEntityTypes($input: GetEntityTypeEntityTypesInput) {
	getEntityTypeEntityTypes(input: $input) {
		count
		rows {
			...EntityTypeEntityTypeListItem
		}
	}
}

# EntityTypeEntityTypeRole
query getEntityTypeEntityTypeRoles($entityTypeEntityTypeId: Int!) {
	getEntityTypeEntityTypeRoles(
		input: {
			filter: { fields: { entityTypeEntityTypeId: { val: $entityTypeEntityTypeId, op: EQUAL } } }
		}
	) {
		count
		rows {
			...EntityTypeEntityTypeRoleListItem
		}
	}
}

# FieldTypes
query getFieldTypes {
	getFieldTypes {
		count
		rows {
			...FieldTypeListItem
		}
	}
}

# EntityTypeField
query getEntityTypeFields($entityTypeId: Int!) {
	getEntityTypeFields(
		input: { filter: { fields: { entityTypeId: { val: $entityTypeId, op: EQUAL } } } }
	) {
		count
		rows {
			...EntityTypeFieldListItem
		}
	}
}

query getEntityTypeField($id: Int!) {
	getEntityTypeFields(input: { filter: { fields: { id: { val: $id, op: EQUAL } } } }) {
		rows {
			...EntityTypeField
		}
	}
}

# Entity
query getEntities($input: GetEntitiesInput!) {
	getEntities(input: $input) {
		count
		rows {
			...EntityListItem
		}
	}
}

query getRelatedEntities($entityId: BigInt!, $relatedTypeId: Int!) {
	getEntities(
		input: {
			filter: {
				and: [
					{ fields: { typeId: { val: $relatedTypeId, op: EQUAL } } }
					{
						or: [
							{ fields: { entityEntities: { entity2Id: { val: $entityId, op: EQUAL } } } }
							{ fields: { entity2EntityEntities: { entity1Id: { val: $entityId, op: EQUAL } } } }
						]
					}
				]
			}
		}
	) {
		count
		rows {
			...RelatedEntityListItem
		}
	}
}

query getEntity($id: BigInt!) {
	getEntities(input: { filter: { fields: { id: { val: $id, op: EQUAL } } } }) {
		rows {
			...Entity
		}
	}
}

# Address
query getAddresses {
	getAddresses {
		count
		rows {
			...AddressListItem
		}
	}
}

# EntityTypeAddressRole
query getEntityTypeAddressRoles($entityTypeId: Int!) {
	getEntityTypeAddressRoles(
		input: { filter: { fields: { entityTypeId: { val: $entityTypeId, op: EQUAL } } } }
	) {
		count
		rows {
			...EntityTypeAddressRoleListItem
		}
	}
}

# EntityAddress
query getEntityAddresses($entityId: BigInt!) {
	getEntityAddresses(input: { filter: { fields: { entityId: { val: $entityId, op: EQUAL } } } }) {
		count
		rows {
			...EntityAddressListItem
		}
	}
}

# EntityFile
query getEntityFiles($entityId: BigInt!) {
	getEntityFiles(input: { filter: { fields: { entityId: { val: $entityId, op: EQUAL } } } }) {
		count
		rows {
			...EntityFileListItem
		}
	}
}

# EntityTypeLogType
query getEntityTypeLogTypes($entityTypeId: Int!) {
	getEntityTypeLogTypes(
		input: { filter: { fields: { entityTypeId: { val: $entityTypeId, op: EQUAL } } } }
	) {
		count
		rows {
			...EntityTypeLogTypeListItem
		}
	}
}

# EntityLog
query getEntityLogs($entityId: BigInt!) {
	getEntityLogs(
		input: {
			filter: {
				fields: { entityId: { val: $entityId, op: EQUAL }, deletedAt: { val: null, op: EQUAL } }
			}
		}
	) {
		count
		rows {
			...EntityLogListItem
		}
	}
}

# SearchAllView
query getSearchAllViews($text: NullableString) {
	getSearchAllViews(input: { filter: { fields: { text: { val: $text, op: LIKE } } } }) {
		count
		rows {
			...SearchAllViewListItem
		}
	}
}

# EntityTypeWorkflowSteps
query getEntityTypeWorkflowSteps($entityTypeId: Int!) {
	getEntityTypeWorkflowSteps(
		input: { filter: { fields: { entityTypeId: { val: $entityTypeId, op: EQUAL } } } }
	) {
		count
		rows {
			...EntityTypeWorkflowStepListItem
		}
	}
}
